### PR TITLE
Set default logging level to WARNING

### LINKED ISSUE #1175: Getting debug-like log messages in console after upgrade to v1.4.0
**Describe the bug**

After upgrading to v1.4.0, I suddenly get the following console messages when running `pipx` commands:

```sh
$ pipx list
pipx version is 1.4.0
Default python interpreter is '/opt/homebrew/opt/python@3.12/libexec/bin/python'
running <checking pip's availability>
Time since last upgrade of shared libs, in seconds: 2674. Upgrade will be run by pipx if greater than 2592000.
running <checking pip's availability>
running <checking pip's availability>
running <checking pip's availability>
running <checking pip's availability>
running <checking pip's availability>
running <checking pip's availability>
running <checking pip's availability>
running <checking pip's availability>
...
```

The excessive log messages will go away when adding one level of `-q` flag to `pipx`.

On a first glance, the message `running <checking pip's availability>` is logged with `logger.info()`. Not sure, if that's really meant to be a info and not debug message though. But that log message call has not been changed for a long time. Maybe there’s a side effect with one of the recent log level changes that went into v1.4.

**How to reproduce**

Run `pipx list` without `-q` or `-v` flags.

**Expected behavior**

Show console log messages as it was pre v1.4.

**Environment**

```sh
$ pipx environment
pipx version is 1.4.0
Default python interpreter is '/opt/homebrew/opt/python@3.12/libexec/bin/python'
Environment variables (set by user):

PIPX_HOME=
PIPX_BIN_DIR=
PIPX_MAN_DIR=
PIPX_SHARED_LIBS=
PIPX_DEFAULT_PYTHON=
USE_EMOJI=

Derived values (computed by pipx):

PIPX_HOME=/Users/tspng/.local/pipx
PIPX_BIN_DIR=/Users/tspng/.local/bin
PIPX_MAN_DIR=/Users/tspng/.local/share/man
PIPX_SHARED_LIBS=/Users/tspng/.local/pipx/shared
PIPX_LOCAL_VENVS=/Users/tspng/.local/pipx/venvs
PIPX_LOG_DIR=/Users/tspng/.local/pipx/logs
PIPX_TRASH_DIR=/Users/tspng/.local/pipx/.trash
PIPX_VENV_CACHEDIR=/Users/tspng/.local/pipx/.cache
PIPX_DEFAULT_PYTHON=/opt/homebrew/opt/python@3.12/libexec/bin/python
USE_EMOJI=true
```

### LINKED ISSUE #1177: Running `pipx` without any arguments errors on `1.4.0`
**Describe the bug**

Running `pipx` without any args in `1.3.3` prints the help:

```
❯ pipx
usage: pipx [-h] [--version] {install,uninject,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall,reinstall-all,list,run,runpip,ensurepath,environment,completions} ...

Install and execute apps from Python packages.

Binaries can either be installed globally into isolated Virtual Environments
or run directly in a temporary Virtual Environment.
```

in `1.4.0` it errors with:
```
❯ pipx
Traceback (most recent call last):
  File "/opt/homebrew/bin/pipx", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/Cellar/pipx/1.4.0/libexec/lib/python3.12/site-packages/pipx/main.py", line 905, in cli
    setup(parsed_pipx_args)
  File "/opt/homebrew/Cellar/pipx/1.4.0/libexec/lib/python3.12/site-packages/pipx/main.py", line 843, in setup
    verbose = args.verbose - args.quiet
              ^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'verbose'
```
**How to reproduce**

Run `pipx` against latest version with no args. Installed with homebrew. Python 3.12.

**Expected behavior**

Should print the same as `pipx --help`, which works on `1.4.0`

### PR DESCRIPTION
**Pull request by dukecat0**
- [x] I have added an entry to `docs/changelog.md`

## Summary of changes
Set the default logging level to WARNING, so debug log messages won't be shown without passing additional flags such as `--verbose`.

Closes #1175
Closes #1177 

## Test plan

Tested by running

```
nox -s tests-3.12
```

### CODE REVIEW

File: src/pipx/main.py [hunk 1]
```diff
@@ -840,7 +840,7 @@ def setup(args: argparse.Namespace) -> None:
         print_version()
         sys.exit(0)
 
-    verbose = args.verbose - args.quiet
+    verbose = getattr(args, "verbose", 0) - getattr(args, "quiet", 0)
```
Comment (chrysle) [inline src/pipx/main.py:843]: Or we could set argparses' [`default`](https://docs.python.org/3/library/argparse.html#default) keyword argument?

Comment (dukecat0) [reply src/pipx/main.py:843]: It's set to 0 already: https://github.com/pypa/pipx/blob/98635d27d93aff9f74bfca660ae81115d3d37d86/src/pipx/main.py#L724

Comment (chrysle) [reply src/pipx/main.py:843]: Then I don't understand why this change is needed.

Comment (dukecat0) [reply src/pipx/main.py:843]: See #1177

Comment (chrysle) [reply src/pipx/main.py:843]: Yes, but `argparse` is supposed to fill in that argument with the default value, isn't it?

I think I've found the culprit: We use a shared parser for defining the verbose and quiet arguments, but don't apply that as a parent parser for the base parser. Thus, the following patch should work:

```patch
diff --git a/src/pipx/main.py b/src/pipx/main.py
index 11e01e5..7dc5d75 100644
--- a/src/pipx/main.py
+++ b/src/pipx/main.py
@@ -720,12 +720,6 @@ def get_command_parser() -> argparse.ArgumentParser:
 
     completer_venvs = InstalledVenvsCompleter(venv_container)
 
-    parser = argparse.ArgumentParser(
-        prog=prog_name(),
-        formatter_class=LineWrapRawTextHelpFormatter,
-        description=PIPX_DESCRIPTION,
-    )
-    parser.man_short_description = PIPX_DESCRIPTION.splitlines()[1]  # type: ignore
 
     shared_parser = argparse.ArgumentParser(add_help=False)
 
@@ -744,6 +738,14 @@ def get_command_parser() -> argparse.ArgumentParser:
         "--verbose", "-v", action="count", default=0, help=("Give more output.")
     )
 
+    parser = argparse.ArgumentParser(
+        prog=prog_name(),
+        formatter_class=LineWrapRawTextHelpFormatter,
+        description=PIPX_DESCRIPTION,
+        parents=[shared_parser],
+    )
+    parser.man_short_description = PIPX_DESCRIPTION.splitlines()[1]  # type: ignore
+
     subparsers = parser.add_subparsers(
         dest="command", description="Get help for commands with pipx COMMAND --help"
     )
```

Comment (dukecat0) [reply src/pipx/main.py]: Done

**Review by chrysle — APPROVED** [review]

**Comment by dukecat0** [comment]
Probably we need to update this line to `ERROR and CRITICAL logging levels.`?
https://github.com/pypa/pipx/blob/81c2fa509768715de24a3ba10d46596de980052f/src/pipx/main.py#L720

**Comment by chrysle** [comment]
Yes, looks like it.

**Comment by mayeut** [comment]
The `"-q"` added in #1159 shall also be removed:
https://github.com/pypa/pipx/blob/81c2fa509768715de24a3ba10d46596de980052f/tests/test_list.py#L83

**Comment by dukecat0** [comment]
We can change its behavior instead of removing it. I remember the original usage of this flag was hiding all console outputs, not just the debug log messages.

**Comment by mayeut** [comment]
> We can change its behavior instead of removing it. I remember the original usage of this flag was hiding all console outputs, not just the debug log messages.

It might be so but:
IMHO, it should have raised a red flag in review (but can be easily missed).
Removing the flag in that test allows to see that the default log level is the correct one (for now, it seems it's the only test for that - although probably accidental).
Given this PR reverts the default log level to WARNING, I think we should also revert this change that was only introduced because of the default log level change.

If there are more changes to be made as you suggest, then it would be for another PR but for now, I think changing back this test is the best option.

**Comment by dukecat0** [comment]
I've opened #1181 to revert it now.
