### ISSUE TITLE
Running `pipx` without any arguments errors on `1.4.0`

### ISSUE THREAD

**Issue by willbowditch** [pypa/pipx#1177]
**Describe the bug**

Running `pipx` without any args in `1.3.3` prints the help:

```
❯ pipx
usage: pipx [-h] [--version] {install,uninject,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall,reinstall-all,list,run,runpip,ensurepath,environment,completions} ...

Install and execute apps from Python packages.

Binaries can either be installed globally into isolated Virtual Environments
or run directly in a temporary Virtual Environment.
```

in `1.4.0` it errors with:
```
❯ pipx
Traceback (most recent call last):
  File "/opt/homebrew/bin/pipx", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/Cellar/pipx/1.4.0/libexec/lib/python3.12/site-packages/pipx/main.py", line 905, in cli
    setup(parsed_pipx_args)
  File "/opt/homebrew/Cellar/pipx/1.4.0/libexec/lib/python3.12/site-packages/pipx/main.py", line 843, in setup
    verbose = args.verbose - args.quiet
              ^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'verbose'
```
**How to reproduce**

Run `pipx` against latest version with no args. Installed with homebrew. Python 3.12.

**Expected behavior**

Should print the same as `pipx --help`, which works on `1.4.0`

**Comment by dimk00z** [comment]
I have the same thing
